### ISSUE TITLE
Model TODO list:

### ISSUE THREAD

**Issue by GreatAlexander** [ipab-rad/ICRIN#10]
- [x] Create Model class
- [x] Interface with RVO library
- [x] Test multi-simulation RVO Wrapper methods.
- [ ] Test virtual environment setup.
- [x] Setup parallelization: parfor simulation loops (Rather than agent parfors).
- [x] Implement inference algorithm (InferGoals)
- [x] Produce Simulation Velocities (RunSims)
- [x] Goal Sampling
- [x] Goal Sequence
- [ ] Awareness
- [x] Test goal prediction results.
- [x] Test simultaneous multiple agents.
- [ ] Consider tracker ids for better intention inference
- [ ] When calc_pref_velocities for unmodelled agents inside simulation, allow to either set curr_velocity or use most likely goal for such agent (Optional: unknown side-effects of latter)
- [ ] Using decimal points on the goal x or y breaks the model!

---
- [ ] Probabilistic Programming (Figaro) seems awesome. IMPLEMENT IT!

**Comment by GreatAlexander** [comment]
Simulation paralellisation is setup, but did not significantly reduce processing time. It is believed this difference was not more significant due to the small number of parallel simulations executed (4 agents, 3 goals). Will check again with goal sampling.
UPDATE: It was since found out that parallelisation did not work as expected (i.e. Simulation per CPU thread). More investigation is needed to figure out how best to achieve this and when best to use it (e.g. for Interactive Costmap generation?)
