### ISSUE TITLE
Environment TODO list:

### ISSUE THREAD

**Issue by GreatAlexander** [ipab-rad/ICRIN#11]
- [x] Create new agents using planner_wrapper.
- [x] Process tracker/robot_comms data and feed to planner_wrapper.
- [x] Implement bumper_wrapper and appropriate robot safety protocols.
- [x] Environment to load goals/plans from Experiment topic.
- [ ] Enable "Virtual" environment for modelling without planning agent (i.e. robot).
