### ISSUE TITLE
Planner TODO List:

### ISSUE THREAD

**Issue by GreatAlexander** [ipab-rad/ICRIN#19]
- [x] Read RVO Parameters from Parameter server
- [x] Integration with ROS Navigation
- [x] Generate costmaps dynamically
- [x] Use model data to create costmaps
